In [2]:
import parser

import numpy as np

In [184]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array((0.1, 0.2, 0.3, 0.4))

In [185]:
a1

array([1, 2, 3, 4])

In [186]:
type(a1)

numpy.ndarray

In [188]:
a1.dtype

dtype('int32')

In [189]:
a1.dtype

dtype('int32')

In [9]:
a2.dtype

dtype('float64')

In [10]:
a = np.array([1, 2, 3, 4], dtype=np.uint8)

In [11]:
a = np.array([1, 2, 3, 300], dtype=np.uint8)

In [12]:
a

array([ 1,  2,  3, 44], dtype=uint8)

In [13]:
np.array([255], dtype=np.uint8)

array([255], dtype=uint8)

In [14]:
np.array([256], dtype=np.uint8)


array([0], dtype=uint8)

In [15]:
np.array([257], dtype=np.uint8)


array([1], dtype=uint8)

In [16]:
np.array([128], dtype=np.int8)

array([-128], dtype=int8)

In [17]:
np.array([127], dtype=np.int8)


array([127], dtype=int8)

In [18]:
np.array([129], dtype=np.int8)


array([-127], dtype=int8)

In [19]:
a = np.array([1, 2, 3, 3.14])

In [20]:
a

array([1.  , 2.  , 3.  , 3.14])

In [21]:
np.array([1, 2, 9.9, 9.1], dtype=np.int64)

array([1, 2, 9, 9], dtype=int64)

In [23]:
m_py = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
]

In [24]:
m1 = np.array(m_py, dtype=np.int16)

In [25]:
m1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [26]:
a = np.array([1, 2, 3])
m2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
)

In [28]:
a

array([1, 2, 3])

In [29]:
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
m1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [31]:
m1.size

9

In [32]:
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
m2.size

12

In [34]:
a.shape

(3,)

In [35]:
m1.shape

(3, 3)

In [36]:
m2.shape

(4, 3)

In [37]:
a = np.zeros(5)

In [38]:
a

array([0., 0., 0., 0., 0.])

In [39]:
a.dtype

dtype('float64')

In [41]:
a = np.zeros(5, dtype=int)

In [42]:
a.dtype

dtype('int32')

In [43]:
a

array([0, 0, 0, 0, 0])

In [44]:
m = np.zeros((4, 3), dtype=np.uint8)

In [45]:
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [46]:
m.shape

(4, 3)

In [47]:
m = np.ones((4, 3), dtype=np.uint8)


In [48]:
m

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [51]:
m = np.ones((10, 2), dtype=float)

In [52]:
m

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [53]:
m = np.full((2, 5), 3.14)

In [54]:
m

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [55]:
m = np.eye(5)

In [56]:
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
m.dtype

dtype('float64')

In [58]:
m = np.eye(4, dtype=int)

In [59]:
m

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [60]:
list(range(2, 11, 2))

[2, 4, 6, 8, 10]

In [62]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [190]:
np.linspace(2, 10, num=10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [191]:
np.linspace(2, 10, 10)


array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [192]:
import math

x_coords = np.linspace(-2 * math.pi, 2 * math.pi, 50)

In [193]:
x_coords

array([-6.28318531, -6.02672876, -5.77027222, -5.51381568, -5.25735913,
       -5.00090259, -4.74444605, -4.48798951, -4.23153296, -3.97507642,
       -3.71861988, -3.46216333, -3.20570679, -2.94925025, -2.6927937 ,
       -2.43633716, -2.17988062, -1.92342407, -1.66696753, -1.41051099,
       -1.15405444, -0.8975979 , -0.64114136, -0.38468481, -0.12822827,
        0.12822827,  0.38468481,  0.64114136,  0.8975979 ,  1.15405444,
        1.41051099,  1.66696753,  1.92342407,  2.17988062,  2.43633716,
        2.6927937 ,  2.94925025,  3.20570679,  3.46216333,  3.71861988,
        3.97507642,  4.23153296,  4.48798951,  4.74444605,  5.00090259,
        5.25735913,  5.51381568,  5.77027222,  6.02672876,  6.28318531])

In [67]:
y_values = np.array([math.sin(x) for x in x_coords])

In [68]:
y_values

array([ 2.44929360e-16,  2.53654584e-01,  4.90717552e-01,  6.95682551e-01,
        8.55142763e-01,  9.58667853e-01,  9.99486216e-01,  9.74927912e-01,
        8.86599306e-01,  7.40277997e-01,  5.45534901e-01,  3.15108218e-01,
        6.40702200e-02, -1.91158629e-01, -4.33883739e-01, -6.48228395e-01,
       -8.20172255e-01, -9.38468422e-01, -9.95379113e-01, -9.87181783e-01,
       -9.14412623e-01, -7.81831482e-01, -5.98110530e-01, -3.75267005e-01,
       -1.27877162e-01,  1.27877162e-01,  3.75267005e-01,  5.98110530e-01,
        7.81831482e-01,  9.14412623e-01,  9.87181783e-01,  9.95379113e-01,
        9.38468422e-01,  8.20172255e-01,  6.48228395e-01,  4.33883739e-01,
        1.91158629e-01, -6.40702200e-02, -3.15108218e-01, -5.45534901e-01,
       -7.40277997e-01, -8.86599306e-01, -9.74927912e-01, -9.99486216e-01,
       -9.58667853e-01, -8.55142763e-01, -6.95682551e-01, -4.90717552e-01,
       -2.53654584e-01, -2.44929360e-16])

In [69]:
np.random.random(5)

array([0.96115168, 0.21141672, 0.48780131, 0.73584371, 0.41748783])

In [70]:
np.random.seed(0)

In [71]:
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [72]:
np.random.random((5, 3))


array([[0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504],
       [0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215]])

In [194]:
np.random.seed(0)
np.random.randint(1, 10, 5)


array([6, 1, 4, 4, 8])

In [196]:
np.random.seed(0)
np.random.randint(1, 7, (10, 2))


array([[5, 6],
       [1, 4],
       [4, 4],
       [2, 4],
       [6, 3],
       [5, 1],
       [1, 5],
       [3, 2],
       [1, 2],
       [6, 2]])

In [79]:
arr = np.arange(12)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
arr.shape

(12,)

In [82]:
m1 = arr.reshape(4, 3)

In [258]:
m1

array([[ 100, -100,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,  200]])

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
arr[0] = 100

In [86]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [87]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [88]:
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
m1[3][2] = 200

In [90]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10, 200]])

In [91]:
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
m3 = arr.reshape(3, 4).copy()

In [93]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [94]:
arr[1] = -100

In [95]:
arr

array([ 100, -100,    2,    3,    4,    5,    6,    7,    8,    9,   10,
        200])

In [96]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [200]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
]
)

In [99]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
m.shape

(2, 3)

In [205]:
arr2 = m.reshape(1, 6)

In [206]:
arr2

array([[1, 2, 3, 4, 5, 6]])

In [207]:
arr2[2] = 300
arr2

IndexError: index 2 is out of bounds for axis 0 with size 1

In [104]:
m

array([[  1,   2, 300],
       [  4,   5,   6]])

In [105]:
a1 = np.arange(1, 6)

In [106]:
a1

array([1, 2, 3, 4, 5])

In [208]:
a2 = np.arange(1, 11).reshape(2, 5)

In [209]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [210]:
s1 = np.vstack((a1, a2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [110]:
s1

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [112]:
try:
    np.vstack((np.arange(3), a2))
except ValueError as ex:
    print(ex)

all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5


In [114]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([0.1, 0.2, 0.3, 0.4])
result = np.vstack((a1, a2))

In [115]:
result

array([[1. , 2. , 3. , 4. ],
       [0.1, 0.2, 0.3, 0.4]])

In [116]:
result.dtype

dtype('float64')

In [117]:
np.vstack((
    np.arange(5),
    np.linspace(0, 1, 5),
    np.eye(5)
))

array([[0.  , 1.  , 2.  , 3.  , 4.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  ]])

In [118]:
a1

array([1, 2, 3, 4])

In [121]:
a1 = np.array([1, 2], dtype=np.uint8)
a2 = np.array([1, 2], dtype=np.uint64)
a3 = np.array([1, 2], dtype=np.int32)



In [123]:
result = np.vstack([a1, a2, a3])

In [124]:
result

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [125]:
a1

array([1, 2], dtype=uint8)

In [126]:
a1.astype(np.float32)

array([1., 2.], dtype=float32)

In [127]:
result = np.vstack(
    (
        a1.astype(np.int64),
        a2.astype(np.int64),
        a3.astype(np.int64)

    )
)

In [128]:
result

array([[1, 2],
       [1, 2],
       [1, 2]], dtype=int64)

In [129]:
result.dtype

dtype('int64')

In [130]:
a1 = np.linspace(0, 5, 10).reshape(5, 2)
a1

array([[0.        , 0.55555556],
       [1.11111111, 1.66666667],
       [2.22222222, 2.77777778],
       [3.33333333, 3.88888889],
       [4.44444444, 5.        ]])

In [132]:
np.random.seed(0)
a2 = np.random.randint(0, 10, 10).reshape(5, 2)
a2

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4]])

In [133]:
result = np.hstack((a1, a2))

In [134]:
result

array([[0.        , 0.55555556, 5.        , 0.        ],
       [1.11111111, 1.66666667, 3.        , 3.        ],
       [2.22222222, 2.77777778, 7.        , 9.        ],
       [3.33333333, 3.88888889, 3.        , 5.        ],
       [4.44444444, 5.        , 2.        , 4.        ]])

In [136]:
a = [1, 2, 3, 4]
a[2]

3

In [138]:
m = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [139]:
m[1]

[4, 5, 6]

In [140]:
m[1][2]

6

In [141]:
m[1][2] = 100
m

[[1, 2, 3], [4, 5, 100], [7, 8, 9]]

In [143]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [144]:
a[0]

1

In [145]:
a[1] = 200

In [146]:
a

array([  1, 200,   3])

In [147]:
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
m[1][1]

1.0

In [149]:
m[1][2] = 100
m

array([[  1.,   0.,   0.],
       [  0.,   1., 100.],
       [  0.,   0.,   1.]])

In [150]:
m[1, 2]

100.0

In [152]:
m[1, 2] = 300
m

array([[  1.,   0.,   0.],
       [  0.,   1., 300.],
       [  0.,   0.,   1.]])

In [153]:
arr = np.array([1, 2, 3, 4], dtype=np.uint8)

In [154]:
arr[3] = -100

In [155]:
arr

array([  1,   2,   3, 156], dtype=uint8)

In [156]:
l = [1, 2, 3, 4, 5, 6]
l[0:3]

[1, 2, 3]

In [157]:
l[0::2]

[1, 3, 5]

In [158]:
l[::-1]

[6, 5, 4, 3, 2, 1]

In [160]:
arr = np.array(l)

In [161]:
arr

array([1, 2, 3, 4, 5, 6])

In [162]:
arr[0::2]

array([1, 3, 5])

In [163]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [164]:
l

[1, 2, 3, 4, 5, 6]

In [165]:
slice_ = l[0:2]
slice_

[1, 2]

In [166]:
slice_[0] = 100

In [168]:
slice_

[100, 2]

In [169]:
l

[1, 2, 3, 4, 5, 6]

In [170]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [171]:
slice_ = arr[0:2]
slice_

array([1, 2])

In [172]:
slice_[0] = 100
slice_

array([100,   2])

In [173]:
l

[1, 2, 3, 4, 5, 6]

In [174]:
arr

array([100,   2,   3,   4,   5,   6])

In [176]:
arr = np.arange(1, 7)
slice_ = arr[3:]

In [177]:
slice_

array([4, 5, 6])

In [178]:
arr[-1] = 60
arr

array([ 1,  2,  3,  4,  5, 60])

In [179]:
slice_

array([ 4,  5, 60])

In [180]:
arr = np.arange(1, 7)
slice_ = arr[3:].copy()
slice_


array([4, 5, 6])

In [181]:
slice_[-1] = 60

In [182]:
slice_

array([ 4,  5, 60])

In [183]:
arr

array([1, 2, 3, 4, 5, 6])

In [211]:
arr = np.random.randint(1, 7, (2, 5))

In [212]:
arr

array([[6, 1, 2, 5, 4],
       [1, 4, 6, 1, 3]])

In [215]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [216]:
sub = np.array([arr[0], arr[2], arr[3]])

In [217]:
sub

array([10, 30, 40])

In [218]:
sub = arr[np.array([0, 2, 3])]

In [219]:
sub

array([10, 30, 40])

In [222]:
try:
    sub = arr[[0, 2, 3]]
except Exception as ex:
    print(type(ex), ex)

In [223]:
sub

array([10, 30, 40])

In [224]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [225]:
sub

array([10, 30, 40])

In [226]:
sub[1] = 300

In [227]:
sub

array([ 10, 300,  40])

In [228]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [229]:
arr = np.arange(1, 10)

In [230]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
arr[np.array([0, 1, 1, 5])]

array([1, 2, 2, 6])

In [232]:
arr[np.array(
    [
        [0, 1],
        [1, 5]
    ]
)]

array([[1, 2],
       [2, 6]])

In [233]:
m = np.arange(25).reshape(5, 5)

In [234]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [235]:
sub = m[
    [0, 1, 3],
]

In [236]:
sub

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [237]:
m[[0, 1, 3], 2]

array([ 2,  7, 17])

In [238]:
m[[0, 1, 3], 0::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [15, 17, 19]])

In [239]:
import csv

In [242]:
with open('AAPL.csv') as f:
    reader = csv.reader(f, skipinitialspace=True)
    headers = next(reader)
    data = list(reader)

In [243]:
headers

['Symbol', 'Date', 'Close', 'Volume', 'Open', 'High', 'Low']

In [244]:
data

[['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93', '112.2'],
 ['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43', '111.1'],
 ['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28', '114.5399'],
 ['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55', '112.88'],
 ['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55', '114.28'],
 ['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04', '114.59'],
 ['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705', '116.45'],
 ['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98', '115.63'],
 ['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419', '115.66'],
 ['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548', '118.81'],
 ['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2', '118.15'],
 ['AAPL', '10/14/2020', '121.19', '151062300', '121', '123.03', '119.62'],
 ['AAPL', '10/13/2020', '121.1', '262330500', '125.27', '125.39', '119.

In [245]:
data = np.array(data)
data

array([['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93',
        '112.2'],
       ['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43',
        '111.1'],
       ['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28',
        '114.5399'],
       ['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55',
        '112.88'],
       ['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55',
        '114.28'],
       ['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04',
        '114.59'],
       ['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705',
        '116.45'],
       ['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98',
        '115.63'],
       ['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419',
        '115.66'],
       ['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548',
        '118.81'],
       ['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2',
        '11

In [246]:
dates = data[:, 1]
dates

array(['10/29/2020', '10/28/2020', '10/27/2020', '10/26/2020',
       '10/23/2020', '10/22/2020', '10/21/2020', '10/20/2020',
       '10/19/2020', '10/16/2020', '10/15/2020', '10/14/2020',
       '10/13/2020', '10/12/2020', '10/09/2020', '10/08/2020',
       '10/07/2020', '10/06/2020', '10/05/2020', '10/02/2020',
       '10/01/2020', '09/30/2020', '09/29/2020'], dtype='<U10')

In [247]:
from dateutil import parser

In [248]:
dates = [parser.parse(d) for d in dates]
dates

[datetime.datetime(2020, 10, 29, 0, 0),
 datetime.datetime(2020, 10, 28, 0, 0),
 datetime.datetime(2020, 10, 27, 0, 0),
 datetime.datetime(2020, 10, 26, 0, 0),
 datetime.datetime(2020, 10, 23, 0, 0),
 datetime.datetime(2020, 10, 22, 0, 0),
 datetime.datetime(2020, 10, 21, 0, 0),
 datetime.datetime(2020, 10, 20, 0, 0),
 datetime.datetime(2020, 10, 19, 0, 0),
 datetime.datetime(2020, 10, 16, 0, 0),
 datetime.datetime(2020, 10, 15, 0, 0),
 datetime.datetime(2020, 10, 14, 0, 0),
 datetime.datetime(2020, 10, 13, 0, 0),
 datetime.datetime(2020, 10, 12, 0, 0),
 datetime.datetime(2020, 10, 9, 0, 0),
 datetime.datetime(2020, 10, 8, 0, 0),
 datetime.datetime(2020, 10, 7, 0, 0),
 datetime.datetime(2020, 10, 6, 0, 0),
 datetime.datetime(2020, 10, 5, 0, 0),
 datetime.datetime(2020, 10, 2, 0, 0),
 datetime.datetime(2020, 10, 1, 0, 0),
 datetime.datetime(2020, 9, 30, 0, 0),
 datetime.datetime(2020, 9, 29, 0, 0)]

In [249]:
headers

['Symbol', 'Date', 'Close', 'Volume', 'Open', 'High', 'Low']

In [250]:
oc = data[:, np.array([4, 2])]

In [251]:
oc

array([['112.37', '115.32'],
       ['115.05', '111.2'],
       ['115.49', '116.6'],
       ['114.01', '115.05'],
       ['116.39', '115.04'],
       ['117.45', '115.75'],
       ['116.67', '116.87'],
       ['116.2', '117.51'],
       ['119.96', '115.98'],
       ['121.28', '119.02'],
       ['118.72', '120.71'],
       ['121', '121.19'],
       ['125.27', '121.1'],
       ['120.06', '124.4'],
       ['115.28', '116.97'],
       ['116.25', '114.97'],
       ['114.62', '115.08'],
       ['115.7', '113.16'],
       ['113.91', '116.5'],
       ['112.89', '113.02'],
       ['117.64', '116.79'],
       ['113.79', '115.81'],
       ['114.55', '114.09']], dtype='<U10')

In [253]:
oc = data[:, np.array([4, 2])].astype(float)
oc


array([[112.37, 115.32],
       [115.05, 111.2 ],
       [115.49, 116.6 ],
       [114.01, 115.05],
       [116.39, 115.04],
       [117.45, 115.75],
       [116.67, 116.87],
       [116.2 , 117.51],
       [119.96, 115.98],
       [121.28, 119.02],
       [118.72, 120.71],
       [121.  , 121.19],
       [125.27, 121.1 ],
       [120.06, 124.4 ],
       [115.28, 116.97],
       [116.25, 114.97],
       [114.62, 115.08],
       [115.7 , 113.16],
       [113.91, 116.5 ],
       [112.89, 113.02],
       [117.64, 116.79],
       [113.79, 115.81],
       [114.55, 114.09]])

In [254]:
diffs = oc[:, 1] - oc[:, 0]
diffs

array([ 2.95, -3.85,  1.11,  1.04, -1.35, -1.7 ,  0.2 ,  1.31, -3.98,
       -2.26,  1.99,  0.19, -4.17,  4.34,  1.69, -1.28,  0.46, -2.54,
        2.59,  0.13, -0.85,  2.02, -0.46])

In [255]:
diff_percs = ((oc[:, 1] - oc[:, 0]) / oc[:, 0]) * 100

In [256]:
diff_percs

array([ 2.62525585, -3.34637114,  0.96112218,  0.91220068, -1.15989346,
       -1.44742444,  0.17142367,  1.12736661, -3.31777259, -1.86345646,
        1.67621294,  0.15702479, -3.32880977,  3.61485924,  1.46599584,
       -1.10107527,  0.40132612, -2.19533276,  2.27372487,  0.11515635,
       -0.72254335,  1.77519993, -0.40157137])

In [259]:
m = np.array([-1, 1, -2, 2, -3, 3])

In [260]:
m

array([-1,  1, -2,  2, -3,  3])

In [261]:
np.less(m, 0)

array([ True, False,  True, False,  True, False])

In [262]:
m < 0

array([ True, False,  True, False,  True, False])

In [263]:
mask = m > 0

In [264]:
mask

array([False,  True, False,  True, False,  True])

In [265]:
m[mask]

array([1, 2, 3])

In [266]:
m = np.array(
    [
        [-1, 1, -2, 2],
        [-3, 3, -4, 4],
        [-5, 5, -6, 6]
    ]
)

In [268]:
negative_numbers = m[m < 0]

In [269]:
negative_numbers

array([-1, -2, -3, -4, -5, -6])

In [272]:
arr = np.arange(-5, 6)

In [273]:
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [274]:
arr[(arr > 0) & (arr < 4)]

array([1, 2, 3])

In [275]:
arr[~(arr < 0)]

array([0, 1, 2, 3, 4, 5])

In [277]:
with open('AAPL.csv') as f:
    reader = csv.reader(f, skipinitialspace=True)
    headers = next(reader)
    data = list(reader)
print(headers)
for row in data:
    print(row)



['Symbol', 'Date', 'Close', 'Volume', 'Open', 'High', 'Low']
['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93', '112.2']
['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43', '111.1']
['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28', '114.5399']
['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55', '112.88']
['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55', '114.28']
['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04', '114.59']
['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705', '116.45']
['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98', '115.63']
['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419', '115.66']
['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548', '118.81']
['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2', '118.15']
['AAPL', '10/14/2020', '121.19', '151062300', '121', '123.03', '119.62']
['AAPL', '10/13/2020', '121.1', '2

In [278]:
arr = np.array(data)
arr

array([['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93',
        '112.2'],
       ['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43',
        '111.1'],
       ['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28',
        '114.5399'],
       ['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55',
        '112.88'],
       ['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55',
        '114.28'],
       ['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04',
        '114.59'],
       ['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705',
        '116.45'],
       ['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98',
        '115.63'],
       ['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419',
        '115.66'],
       ['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548',
        '118.81'],
       ['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2',
        '11

In [279]:
dates = np.array([parser.parse(dt) for dt in arr[:, 1]])

In [280]:
dates

array([datetime.datetime(2020, 10, 29, 0, 0),
       datetime.datetime(2020, 10, 28, 0, 0),
       datetime.datetime(2020, 10, 27, 0, 0),
       datetime.datetime(2020, 10, 26, 0, 0),
       datetime.datetime(2020, 10, 23, 0, 0),
       datetime.datetime(2020, 10, 22, 0, 0),
       datetime.datetime(2020, 10, 21, 0, 0),
       datetime.datetime(2020, 10, 20, 0, 0),
       datetime.datetime(2020, 10, 19, 0, 0),
       datetime.datetime(2020, 10, 16, 0, 0),
       datetime.datetime(2020, 10, 15, 0, 0),
       datetime.datetime(2020, 10, 14, 0, 0),
       datetime.datetime(2020, 10, 13, 0, 0),
       datetime.datetime(2020, 10, 12, 0, 0),
       datetime.datetime(2020, 10, 9, 0, 0),
       datetime.datetime(2020, 10, 8, 0, 0),
       datetime.datetime(2020, 10, 7, 0, 0),
       datetime.datetime(2020, 10, 6, 0, 0),
       datetime.datetime(2020, 10, 5, 0, 0),
       datetime.datetime(2020, 10, 2, 0, 0),
       datetime.datetime(2020, 10, 1, 0, 0),
       datetime.datetime(2020, 9, 30, 0, 

In [281]:
ohlc = arr[:, [4, 5, 6, 2]].astype(float)
ohlc

array([[112.37  , 116.93  , 112.2   , 115.32  ],
       [115.05  , 115.43  , 111.1   , 111.2   ],
       [115.49  , 117.28  , 114.5399, 116.6   ],
       [114.01  , 116.55  , 112.88  , 115.05  ],
       [116.39  , 116.55  , 114.28  , 115.04  ],
       [117.45  , 118.04  , 114.59  , 115.75  ],
       [116.67  , 118.705 , 116.45  , 116.87  ],
       [116.2   , 118.98  , 115.63  , 117.51  ],
       [119.96  , 120.419 , 115.66  , 115.98  ],
       [121.28  , 121.548 , 118.81  , 119.02  ],
       [118.72  , 121.2   , 118.15  , 120.71  ],
       [121.    , 123.03  , 119.62  , 121.19  ],
       [125.27  , 125.39  , 119.65  , 121.1   ],
       [120.06  , 125.18  , 119.2845, 124.4   ],
       [115.28  , 117.    , 114.92  , 116.97  ],
       [116.25  , 116.4   , 114.5901, 114.97  ],
       [114.62  , 115.55  , 114.13  , 115.08  ],
       [115.7   , 116.12  , 112.25  , 113.16  ],
       [113.91  , 116.65  , 113.55  , 116.5   ],
       [112.89  , 115.37  , 112.22  , 113.02  ],
       [117.64  , 11

In [282]:
ohlc[:, 3] > 116.0

array([False, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True, False,  True, False, False])

In [283]:
ohlc[ohlc[:, 3] > 116.0]

array([[115.49  , 117.28  , 114.5399, 116.6   ],
       [116.67  , 118.705 , 116.45  , 116.87  ],
       [116.2   , 118.98  , 115.63  , 117.51  ],
       [121.28  , 121.548 , 118.81  , 119.02  ],
       [118.72  , 121.2   , 118.15  , 120.71  ],
       [121.    , 123.03  , 119.62  , 121.19  ],
       [125.27  , 125.39  , 119.65  , 121.1   ],
       [120.06  , 125.18  , 119.2845, 124.4   ],
       [115.28  , 117.    , 114.92  , 116.97  ],
       [113.91  , 116.65  , 113.55  , 116.5   ],
       [117.64  , 117.72  , 115.83  , 116.79  ]])

In [284]:
dates[ohlc[:, 3] > 116.0]

array([datetime.datetime(2020, 10, 27, 0, 0),
       datetime.datetime(2020, 10, 21, 0, 0),
       datetime.datetime(2020, 10, 20, 0, 0),
       datetime.datetime(2020, 10, 16, 0, 0),
       datetime.datetime(2020, 10, 15, 0, 0),
       datetime.datetime(2020, 10, 14, 0, 0),
       datetime.datetime(2020, 10, 13, 0, 0),
       datetime.datetime(2020, 10, 12, 0, 0),
       datetime.datetime(2020, 10, 9, 0, 0),
       datetime.datetime(2020, 10, 5, 0, 0),
       datetime.datetime(2020, 10, 1, 0, 0)], dtype=object)

In [285]:
mask = ohlc[:, 3] > 116.0

In [287]:
filtered_data = [

    [date, row]
    for date, row in zip(dates[mask], ohlc[mask])
]
for row in filtered_data:
    print(row)

[datetime.datetime(2020, 10, 27, 0, 0), array([115.49  , 117.28  , 114.5399, 116.6   ])]
[datetime.datetime(2020, 10, 21, 0, 0), array([116.67 , 118.705, 116.45 , 116.87 ])]
[datetime.datetime(2020, 10, 20, 0, 0), array([116.2 , 118.98, 115.63, 117.51])]
[datetime.datetime(2020, 10, 16, 0, 0), array([121.28 , 121.548, 118.81 , 119.02 ])]
[datetime.datetime(2020, 10, 15, 0, 0), array([118.72, 121.2 , 118.15, 120.71])]
[datetime.datetime(2020, 10, 14, 0, 0), array([121.  , 123.03, 119.62, 121.19])]
[datetime.datetime(2020, 10, 13, 0, 0), array([125.27, 125.39, 119.65, 121.1 ])]
[datetime.datetime(2020, 10, 12, 0, 0), array([120.06  , 125.18  , 119.2845, 124.4   ])]
[datetime.datetime(2020, 10, 9, 0, 0), array([115.28, 117.  , 114.92, 116.97])]
[datetime.datetime(2020, 10, 5, 0, 0), array([113.91, 116.65, 113.55, 116.5 ])]
[datetime.datetime(2020, 10, 1, 0, 0), array([117.64, 117.72, 115.83, 116.79])]


In [288]:
date = '10/1/2020'
numbers = [100, 200, 300, 400]

In [290]:
[date, numbers]

['10/1/2020', [100, 200, 300, 400]]

In [291]:
[date, *numbers]

['10/1/2020', 100, 200, 300, 400]

In [293]:
filtered_data = [
    [date, *row]
    for date, row in zip(dates[mask], ohlc[mask])
]
for row in filtered_data:
    print(row)

[datetime.datetime(2020, 10, 27, 0, 0), 115.49, 117.28, 114.5399, 116.6]
[datetime.datetime(2020, 10, 21, 0, 0), 116.67, 118.705, 116.45, 116.87]
[datetime.datetime(2020, 10, 20, 0, 0), 116.2, 118.98, 115.63, 117.51]
[datetime.datetime(2020, 10, 16, 0, 0), 121.28, 121.548, 118.81, 119.02]
[datetime.datetime(2020, 10, 15, 0, 0), 118.72, 121.2, 118.15, 120.71]
[datetime.datetime(2020, 10, 14, 0, 0), 121.0, 123.03, 119.62, 121.19]
[datetime.datetime(2020, 10, 13, 0, 0), 125.27, 125.39, 119.65, 121.1]
[datetime.datetime(2020, 10, 12, 0, 0), 120.06, 125.18, 119.2845, 124.4]
[datetime.datetime(2020, 10, 9, 0, 0), 115.28, 117.0, 114.92, 116.97]
[datetime.datetime(2020, 10, 5, 0, 0), 113.91, 116.65, 113.55, 116.5]
[datetime.datetime(2020, 10, 1, 0, 0), 117.64, 117.72, 115.83, 116.79]


In [294]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([5, 4, 3, 2, 1])


In [295]:
arr_1 + arr_2

array([6, 6, 6, 6, 6])

In [296]:
np.add(arr_1, arr_2)

array([6, 6, 6, 6, 6])

In [297]:
np.multiply(arr_1, arr_2)

array([5, 8, 9, 8, 5])

In [299]:
arr_1 % arr_2

array([1, 2, 0, 0, 0], dtype=int32)

In [300]:
arr_1 ** arr_2

array([ 1, 16, 27, 16,  5], dtype=int32)

In [301]:
arr_1 ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [302]:
arr = np.linspace(-2 * np.pi, 2 * np.pi, 10)

In [303]:
arr

array([-6.28318531, -4.88692191, -3.4906585 , -2.0943951 , -0.6981317 ,
        0.6981317 ,  2.0943951 ,  3.4906585 ,  4.88692191,  6.28318531])

In [304]:
np.sin(arr)

array([ 2.44929360e-16,  9.84807753e-01,  3.42020143e-01, -8.66025404e-01,
       -6.42787610e-01,  6.42787610e-01,  8.66025404e-01, -3.42020143e-01,
       -9.84807753e-01, -2.44929360e-16])

In [305]:
np.cos(arr)

array([ 1.        ,  0.17364818, -0.93969262, -0.5       ,  0.76604444,
        0.76604444, -0.5       , -0.93969262,  0.17364818,  1.        ])

In [306]:
from time import perf_counter

In [307]:
l = list(range(1, 1_000_000))

In [308]:
l

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [309]:
start = perf_counter()
new_list = []
for el in l:
    new_list.append(1 / el)
end = perf_counter()
print(f'Elapsed: {end - start}')

Elapsed: 0.1149889000080293


In [310]:

start = perf_counter()
new_list = [1 / el for el in l]
end = perf_counter()
print(f'Elapsed: {end - start}')


Elapsed: 0.07232570000633132


In [311]:
np_l = np.array(l)

In [313]:
np_l.dtype

dtype('int32')

In [315]:
start = perf_counter()
new_arr = 1 / np_l
end = perf_counter()
print(f'Elapsed: {end - start}')

Elapsed: 0.005179799991310574


In [316]:
import random

In [318]:
num_rows = 10_000_000
random.seed(0)
start = perf_counter()
data = [
    [
        random.randint(120, 180),
        random.randint(180, 200),
        random.randint(100, 120),
        random.randint(120, 180)
    ]
    for _ in range(num_rows)
]
end = perf_counter()
print(f'Elapsed: {end - start}')


Elapsed: 30.559192999993684


In [319]:
start = perf_counter()
var = [
    round((row[1] - row[2]) / row[3] * 100)
    for row in data
]
print(var[:5])
end = perf_counter()
print('Elapsed:', end - start)

[65, 56, 52, 55, 51]
Elapsed: 2.7529968000017107


In [320]:
start = perf_counter()
data_np = np.array(data)
end = perf_counter()
print(data_np[:2])
print('Elapsed:', end - start)

[[174 192 113 122]
 [136 196 115 145]]
Elapsed: 7.933167900002445


In [322]:
np.random.seed(0)
start = perf_counter()
data_np = np.hstack(
    [
        np.random.randint(120, 180, (num_rows, 1)),
        np.random.randint(180, 200, (num_rows, 1)),
        np.random.randint(100, 120, (num_rows, 1)),
        np.random.randint(120, 180, (num_rows, 1))
    ]
)
end = perf_counter()
print(data_np[:5])
print('Elapsed: ', end - start)

[[164 181 112 125]
 [167 199 110 136]
 [173 189 106 122]
 [120 180 105 143]
 [123 199 104 122]]
Elapsed:  0.4740938999893842


In [324]:
sales = np.array(
    [
        [10, 0, 5, 3],
        [0, 0, 0, 10],
        [1, 1, 0, 0],
        [3, 0, 4, 5]
    ]
)

In [325]:
unit_price = np.array([100, 50, 20, 10])

In [326]:
unit_cost = np.array([80, 10, 5, 1])

In [328]:
total_sales = sales * unit_price

In [330]:
total_cost = sales * unit_cost
total_cost

array([[800,   0,  25,   3],
       [  0,   0,   0,  10],
       [ 80,  10,   0,   0],
       [240,   0,  20,   5]])

In [331]:
order_net = total_sales - total_cost

In [333]:
order_net

array([[200,   0,  75,  27],
       [  0,   0,   0,  90],
       [ 20,  40,   0,   0],
       [ 60,   0,  60,  45]])

In [334]:
np.sum(order_net)

617

In [335]:
np.amin(np.array([10, 5, 20]))

5

In [336]:
np.amax(np.array([10, 5, 20]))


20

In [337]:
m = np.array([
    [10, 2, 3],
    [11, 8, 7],
    [13, 3, 9],
])

In [338]:
m

array([[10,  2,  3],
       [11,  8,  7],
       [13,  3,  9]])

In [339]:
np.amax(m)

13

In [340]:
np.amin(m)

2

In [341]:
np.amin(m, axis=0)

array([10,  2,  3])

In [342]:
np.amax(m, axis=0)

array([13,  8,  9])

In [343]:
np.median(np.array([1, 2, 3, 4, 5]))

3.0

In [344]:
np.median(np.array([1, 2, 3, 4, 5, 6]))


3.5

In [345]:
m = np.array(
    [
        [1, 10, 100],
        [2, 20, 200],
        [3, 30, 300],
        [3, 30, 300],
        [4, 40, 400]
    ]
)

In [346]:
np.mean(m, axis=0)

array([  2.6,  26. , 260. ])

In [348]:
np.sum(np.arange(1, 10))

45

In [349]:
m = np.arange(1, 10).reshape(3, 3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [350]:
np.sum(m)

45

In [351]:
np.sum(m, axis=0)

array([12, 15, 18])

In [352]:
np.sum(m, axis=1)

array([ 6, 15, 24])

In [353]:
arr = np.array([1.11, 2.22, 5.55, 6.66])
arr

array([1.11, 2.22, 5.55, 6.66])

In [357]:
np.around(arr)

array([1., 2., 6., 7.])

In [358]:
np.random.seed(0)
arr = np.random.randint(1, 10, 20)
arr

array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8, 7, 9, 9, 2, 7, 8, 8, 9, 2, 6])

In [359]:
np.histogram(arr, bins=np.array([0, 2, 4, 6, 8, 9]))

(array([1, 3, 4, 5, 7], dtype=int64), array([0, 2, 4, 6, 8, 9]))

In [360]:
np.histogram(arr, bins=4)

(array([3, 4, 4, 9], dtype=int64), array([1., 3., 5., 7., 9.]))

In [365]:
def freq_distribution(data):
    freq = {}
    for el in data:
        freq[el] = freq.get(el, 0) + 1
    return freq


In [366]:
data = [1, 1, 1, 2, 2, 3]

In [367]:
freq_distribution(data)

{1: 3, 2: 2, 3: 1}

In [368]:
freq_d = freq_distribution(data)
freq_d

{1: 3, 2: 2, 3: 1}

In [369]:
def relative_freq(freq_dist):
    sum_freq = sum(freq_dist.values())
    return {
        k: v / sum_freq * 100 for k, v in freq_dist.items()
    }

In [370]:
relative_f = relative_freq(freq_d)
relative_f

{1: 50.0, 2: 33.33333333333333, 3: 16.666666666666664}

In [371]:
sorted_items = sorted(relative_f.items(), key=lambda x: x[0])
sorted_items

[(1, 50.0), (2, 33.33333333333333), (3, 16.666666666666664)]

In [372]:
relative_f = relative_freq(freq_d)
relative_f

{1: 50.0, 2: 33.33333333333333, 3: 16.666666666666664}

In [373]:
def chart_freq(data):
    pad = max([len(str(el[0])) for el in data])
    for k, v in data:
        print(f"{str(k).rjust(pad)}| {'*' * round(v)}")

In [374]:
chart_freq(sorted_items)

1| **************************************************
2| *********************************
3| *****************


In [375]:
data

[1, 1, 1, 2, 2, 3]

In [376]:
arr = np.array(data, dtype=int)

In [377]:
arr

array([1, 1, 1, 2, 2, 3])

In [379]:
freq, bins = np.histogram(arr, bins=[1, 2, 3, 3])

In [380]:
freq

array([3, 2, 1], dtype=int64)

In [381]:
bins

array([1, 2, 3, 3])

In [382]:
rel = freq / np.sum(freq) * 100

In [383]:
rel

array([50.        , 33.33333333, 16.66666667])

In [384]:
bins

array([1, 2, 3, 3])

In [385]:
data = list(zip(bins.tolist(), rel.tolist()))

In [386]:
data

[(1, 50.0), (2, 33.33333333333333), (3, 16.666666666666664)]

In [387]:
chart_freq(data)

1| **************************************************
2| *********************************
3| *****************


In [435]:
text = 'Andreas'
result = text.rjust(10, '*')
print(result)

***Andreas


In [434]:
votes = {'Charlie': 20, 'Able': 10, 'Baker': 20, 'Dog': 15}

In [391]:
votes_items = votes.items()
votes_items

dict_items([('Charlie', 20), ('Able', 10), ('Baker', 20), ('Dog', 15)])

In [393]:
print(sorted(votes.items(), key=lambda x: x[1]))

[('Able', 10), ('Dog', 15), ('Charlie', 20), ('Baker', 20)]


In [405]:
import random


def freq_distribution(data):
    freq = {}
    for el in data:
        freq[el] = freq.get(el,0) + 1
    return freq

In [406]:
def relative_freq(freq_dist):
    sum_freq = sum(freq_dist.values())
    return {
        k: v / sum_freq * 100 for k, v in freq_dist.items()
    }

In [417]:
def chart_freq(data):
    pad = max([len(str(el)) for el in data])
    for k, v in data:
        print(f"{str(k).rjust(pad)}| {'*' * round(v)}")

In [418]:
def analyze_randint(n, a, b):
    data = [random.randint(a,b) for _ in range(n)]

    freq = freq_distribution(data)
    rel = relative_freq(freq)

    sorted_items = sorted(rel.items(), key= lambda x:x[0])
    chart_free(sorted_items)

In [419]:
random.seed(0)
analyze_randint(10_000, 1,10)

                      1| **********
                      2| **********
                      3| **********
                      4| **********
                      5| **********
                      6| **********
                      7| **********
                      8| **********
                      9| *********
                     10| **********


In [421]:
def np_analyze_randint(n, a, b):
    data = np.random.randint(a,b+1,n)
    bins = np.arange(a,b+2)
    freq, _= np.histogram(data, bins=bins)
    rel = freq/np.sum(freq)*100
    sorted_items = list(zip(bins.tolist(), rel.tolist()))
    print(sorted_items)
    chart_freq(sorted_items)

In [422]:
np.random.seed(0)
np_analyze_randint(10_000,1,10)

[(1, 9.67), (2, 10.32), (3, 9.66), (4, 10.100000000000001), (5, 9.629999999999999), (6, 10.17), (7, 9.84), (8, 9.69), (9, 10.489999999999998), (10, 10.43)]
                      1| **********
                      2| **********
                      3| **********
                      4| **********
                      5| **********
                      6| **********
                      7| **********
                      8| **********
                      9| **********
                     10| **********


In [425]:
def np_chart_freq(keys, values):
    np_len = np.vectorize(len)
    pad = np.amax(np_len(keys))
    for k, v in zip(keys, values):
        print(f"{k.rjust(pad)}| {'*' * v}")

def np_analyze_randint(n, a, b):
    data = np.random.randint(a, b + 1, n)
    bins = np.arange(a, b + 2)
    freq, _ = np.histogram(data, bins=bins)
    rel = np.around(freq / np.sum(freq) * 100)

    np_chart_freq(bins[:-1].astype(str), rel.astype(int))

In [426]:
np.random.seed(0)
np_analyze_randint(10,1,5)

1| ********************
2| **********
3| **********
4| ****************************************
5| ********************


In [427]:
from time import perf_counter

In [431]:
random.seed(0)
start = perf_counter()
analyze_randint(30_000_000, 1, 10)
end = perf_counter()
print('Elapsed:', end - start)

                       1| **********
                       2| **********
                       3| **********
                       4| **********
                       5| **********
                       6| **********
                       7| **********
                       8| **********
                       9| **********
                      10| **********
Elapsed: 23.488705099996878


In [432]:
np.random.seed(0)
start = perf_counter()
np_analyze_randint(30_000_000, 1, 10)
end = perf_counter()
print('Elapsed:', end - start)

 1| **********
 2| **********
 3| **********
 4| **********
 5| **********
 6| **********
 7| **********
 8| **********
 9| **********
10| **********
Elapsed: 1.1713124999951106
